locs_path: 'data/stupino_locs.csv'
interests_path: 'data/stupino_interests.csv'
measure_time: False
n_ids: -1
seed: 1000
id_points_range: [100, 100000000000000000]
load_interests: False
interval_thresh: 0

draw_map: False
draw_gh: False
gh_interests_prec: 18
gh_matrix_prec: 16
gh_bits_per_char: 2

city_center:
  lat: 54.885288
  lon: 38.087027

city_bbox:
  lu: [54.943331, 37.991275]
  rl: [54.840498, 38.214812]

cluster_data_path: None
only_weekday: False
min_slots: 16
number_of_slots: 48
slot_len: 30
min_days: 5
drop_noise: True

model: DBSCAN
dist_policy: 'const'
sample_policy: 'const'
max_dist: 50
min_samples: 15
model_params:
  algorithm: 'ball_tree'
  metric: 'haversine'
  n_jobs: -1
