locs_path: 'data/stupino_locs.csv'
interests_path: 'data/stupino_interests.csv'
cleaned_locs_path: 'data/cleaned_locs_data_21600_4.csv'
measure_time: False
n_ids: -1
seed: 1000
id_points_range: 
 - 100
 - 30000
load_interests: False
interval_thresh: 0


draw_map: False
draw_gh: False
gh_interests_prec: 18
gh_matrix_prec: 16
gh_bits_per_char: 2

city_center:
  lat: 54.885288
  lon: 38.087027

city_bbox:
  lu: [54.943331, 37.991275]
  rl: [54.840498, 38.214812]

cluster_data_path: None
only_weekday: False
min_time_day_thresh: 21600
min_days_thresh: 4
inq_thresh: 31000
drop_noise: True

model: DBSCAN
dist_policy: 'const'
only_hw: True
min_sample_hw: 6
min_sample_interest: 30
max_dist: 100
model_params:
  algorithm: 'ball_tree'
  metric: 'haversine'
  n_jobs: -1
